"""auto-phone-number

Revision ID: cd64bf2e3720
Revises: 1594bf79f3ed
Create Date: 2022-05-21 15:35:47.140710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd64bf2e3720'
down_revision = '1594bf79f3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
